#!/bin/bash
# will be excuted from /etc/udev/rules.d/90-charger.rules

export DISPLAY=:0
export XAUTHORITY=/home/avisek/.Xauthority
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"


notify-send "Boosting Power 🔋!!"
sudo -u avisek XDG_RUNTIME_DIR="/run/user/$(id -u avisek)" polybar-msg action  "#battery.hook.0"
