#!/bin/zsh

if [ "$1" = "crop" ]; then
  SCREENSHOT_DIR=~/Pictures/crop-screenshots
  FILE="$SCREENSHOT_DIR/crop-screenshot-$(date +%Y-%m-%d_%H-%M-%S).png"
  MSG="Crop-Screenshot Saved & Copied"
  SHOT_COMMAND="scrot -s \"$FILE\""
else 
  SCREENSHOT_DIR=~/Pictures/full-screenshots
  FILE="$SCREENSHOT_DIR/full-screenshot-$(date +%Y-%m-%d_%H-%M-%S).png"
  MSG="Full-Screenshot Saved & Copied"
  SHOT_COMMAND="scrot \"$FILE\""
fi

mkdir -p "$SCREENSHOT_DIR"

eval $SHOT_COMMAND && xclip -selection clipboard -t image/png -i "$FILE" 

TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID=""

curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendPhoto" \
     -F "chat_id=${TELEGRAM_CHAT_ID}" \
     -F "photo=@${FILE}"
