return {
	-- {
	-- 	dir = "~/Desktop/nvim/blackhole/",
	-- 	-- "biisal/blackhole",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		require("blackhole").setup({ transparent = true, bg = "#0d0b12" })
	-- 	end,
	-- },
	-- {
	--     "rose-pine/neovim",
	--     name = "rose-pine",
	--     lazy = false,
	--     priority = 1000,
	--     config = function()
	--         require("rose-pine").setup({
	--             variant = "moon",
	--             dark_variant = "moon",
	--
	--             styles = {
	--                 bold = true,
	--                 transparency = true,
	--             },
	--         })
	--
	--         vim.cmd("colorscheme rose-pine")
	--     end
	-- }
}
