#!/bin/bash

[ "$1" == "" ] && echo "Usage: $0 <file> [destination]" && exit 1
DEST="$HOME/Videos/"

[ "$2" != "" ] && DEST="$2"
[ ! -d $DEST ] && echo "Destination $DEST does not exist" && exit 1
EXTENSION="${1##*.}"
[ "$EXTENSION" != "mkv" ] && echo "Only mkv files are supported" && exit 1

FILENAME=$DEST$(basename "$1" .mkv).mp4
ffmpeg -i  "$1" -c:v libx264 -profile:v baseline -level 3.0   -pix_fmt yuv420p -c:a aac -movflags +faststart "$FILENAME"
